// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package database

import (
	"database/sql"
	"time"
)

type Outing struct {
	ID        int32
	Title     string
	Date      time.Time
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	Slug      string
}

type OutingUser struct {
	OutingID int32
	UserID   int32
}

type Photo struct {
	ID        int32
	Path      string
	Title     sql.NullString
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	CreatorID int32
	OutingID  int32
}

type User struct {
	ID           int32
	Username     string
	PasswordHash []byte
	DisplayName  sql.NullString
	AvatarUrl    sql.NullString
	CreatedAt    time.Time
	UpdatedAt    sql.NullTime
}
