// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: query.sql

package database

import (
	"context"
)

const getOne = `-- name: GetOne :one
SELECT 1
`

func (q *Queries) GetOne(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getOne)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}
